### ISSUE TITLE
Add support for modules

### ISSUE THREAD

**Issue by liamg** [liamg/tfsec#18]

**Comment by tadam313** [comment]
Hi @liamg? Wondering what's the state of modules support? 🤔  I gave tfsec a try with the following directory tree:

```
├── main.tf
├── modules
│   ├── deployment
│   │   ├── main.tf
│   │   ├── outputs.tf
│   │   └── variables.tf
│   └── secrets
│       ├── main.tf
│       ├── outputs.tf
│       └── variables.tf
├── outputs.tf
├── README.md
├── terraform.tfvars
└── variables.tf
```
and I had to run `tfsec` twice:

```
tfsec .
tfsec ./modules
```
otherwise it would ignore the embedded code in the modules folder. Is this the expected behaviour or maybe I am doing something wrong 🤔 . Could you please shed some light here?
